let properties = [
    {
        id: 1,
        image: "/img/Tour a Charming Queen Anne House in Defiance, Ohio — Photos _ Apartment Therapy.jpg",
        title: "Charming Queen Anne House",
        purpose: "rent",
        type: "house",
        area: 180,
        rating: 4.8,
        reviews: 24,
        wilaya: "oran",
        description: "F3 house near the beach and the city center, with a beautiful view of the sea and the mountains.",
        price: 10000
    },
    {
        id: 2,
        image: "/img/download (15).jpg",
        title: "Luxury Villa with Private Garden",
        purpose: "sale",
        type: "villa",
        area: 450,
        rating: 4.9,
        reviews: 18,
        wilaya: "algiers",
        description: "Spacious 5-bedroom villa in Hydra with a private swimming pool, garage for 3 cars, and a landscaped garden in a calm neighborhood.",
        price: 85000000
    },
    {
        id: 3,
        image: "/img/Living room inspiration.jpg",
        title: "Cozy Studio in City Center",
        purpose: "rent",
        type: "apartment",
        area: 45,
        rating: 4.2,
        reviews: 31,
        wilaya: "constantine",
        description: "Fully furnished F1 studio apartment near the university campus, ideal for students or working professionals. Includes high-speed internet.",
        price: 35000
    },
    {
        id: 4,
        image: "/img/download (16).jpg",
        title: "Commercial Storefront on Main Street",
        purpose: "rent",
        type: "commercial",
        area: 120,
        rating: 4.6,
        reviews: 12,
        wilaya: "oran",
        description: "Prime commercial space of 120 sqm located in Akid Lotfi. Excellent foot traffic and large display windows for retail or showroom.",
        price: 250000
    },
    {
        id: 5,
        image: "/img/download (17).jpg",
        title: "Spacious F4 Apartment in Residentiel Area",
        purpose: "sale",
        type: "apartment",
        area: 135,
        rating: 4.5,
        reviews: 15,
        wilaya: "tlemcen",
        description: "Beautiful F4 apartment on the 2nd floor with elevator in Mansourah. Close to schools, shops, and transport. Gated community.",
        price: 18500000
    },
    {
        id: 6,
        image: "/img/download (18).jpg",
        title: "Charming Traditional Villa",
        purpose: "sale",
        type: "villa",
        area: 320,
        rating: 4.7,
        reviews: 9,
        wilaya: "tlemcen",
        description: "Authentic Algerian-style villa with an inner courtyard, citrus garden, and traditional tilework near the historic center.",
        price: 42000000
    },
    {
        id: 7,
        image: "/img/download (19).jpg",
        title: "High-Rise Duplex with Terrace",
        purpose: "rent",
        type: "apartment",
        area: 210,
        rating: 4.9,
        reviews: 28,
        wilaya: "algiers",
        description: "Stunning F5 duplex in Sidi Yahia with a private rooftop terrace, open-plan kitchen, 24/7 security, and underground parking.",
        price: 300000
    },
    {
        id: 8,
        image: "/img/download (20).jpg",
        title: "Industrial Warehouse / Storage Unit",
        purpose: "rent",
        type: "commercial",
        area: 500,
        rating: 4.3,
        reviews: 7,
        wilaya: "blida",
        description: "500 sqm secure industrial warehouse near the highway network. High ceilings, heavy vehicle access, and three-phase power.",
        price: 180000
    },
    {
        id: 9,
        image: "/img/download (21).jpg",
        title: "Seaside Summer House",
        purpose: "rent",
        type: "house",
        area: 110,
        rating: 4.8,
        reviews: 42,
        wilaya: "tipaza",
        description: "Furnished F3 beach bungalow with direct terrace access to the beach. Perfect for vacation rentals and weekend getaways.",
        price: 90000
    },
    {
        id: 10,
        image: "/img/download (22).jpg",
        title: "New Built F3 Apartment",
        purpose: "sale",
        type: "apartment",
        area: 95,
        rating: 4.4,
        reviews: 11,
        wilaya: "setif",
        description: "Brand new apartment in Park Mall vicinity. Fitted kitchen, central heating, double glazing, and high-quality ceramic finishes.",
        price: 15500000
    },
    {
        id: 11,
        image: "/img/download (23).jpg",
        title: "Agricultural Land Plot",
        purpose: "sale",
        type: "land",
        area: 5000,
        rating: 4.6,
        reviews: 5,
        wilaya: "mostaganem",
        description: "5000 sqm fertile land plot suitable for farming or countryside estate, with legal title deed (Livret Foncier) and water access.",
        price: 22000000
    },
    {
        id: 12,
        image: "/img/download (24).jpg",
        title: "Modern Office Suite",
        purpose: "rent",
        type: "commercial",
        area: 85,
        rating: 4.7,
        reviews: 19,
        wilaya: "algiers",
        description: "Ready-to-use office space of 85 sqm in Bab Ezzouar business district. Fiber internet infrastructure, conference room, and reception.",
        price: 160000
    },
    {
        id: 13,
        image: "/img/Instagram @ruilamakeup2.jpg",
        title: "Affordable F2 Suburban Apartment",
        purpose: "sale",
        type: "apartment",
        area: 68,
        rating: 4.1,
        reviews: 14,
        wilaya: "annaba",
        description: "Well-maintained F2 apartment in a peaceful neighborhood. Ideal starter home or real estate investment for rental yield.",
        price: 9800000
    },
    {
        id: 14,
        image: "/img/Q' Nest By Quadrillion Hotels Lansdowne.jpg",
        title: "Mountain View Chalet",
        purpose: "rent",
        type: "house",
        area: 160,
        rating: 4.9,
        reviews: 36,
        wilaya: "tizi ouzou",
        description: "Scenic 3-bedroom wooden chalet near Djurdjura mountains. Ideal for nature lovers seeking peace, fresh air, and hiking trails.",
        price: 75000
    },
    {
        id: 15,
        image: "/img/Real Estate Photography _ Vida Residences, Marina Dubai.jpg",
        title: "Contemporary F4 Apartment",
        purpose: "sale",
        type: "apartment",
        area: 150,
        rating: 4.8,
        reviews: 22,
        wilaya: "oran",
        description: "High-end F4 apartment in Belgaid with smart home integration, central air conditioning, and marble floors throughout.",
        price: 24000000
    }
];